// 内置示例词库（用于首次体验，无需联网）
export const SAMPLE_WORDS: { term: string; meaning: string; example?: string }[] = [
  { term: 'abandon', meaning: 'v. 放弃；抛弃', example: 'They had to abandon the plan.' },
  { term: 'ability', meaning: 'n. 能力；才能', example: 'She has the ability to learn fast.' },
  { term: 'absorb', meaning: 'v. 吸收；吸引', example: 'Plants absorb water from soil.' },
  { term: 'abstract', meaning: 'adj. 抽象的 n. 摘要', example: 'Beauty is an abstract concept.' },
  { term: 'academic', meaning: 'adj. 学术的；学院的', example: 'He has a strong academic record.' },
  { term: 'access', meaning: 'n. 通道；使用权 v. 访问', example: 'Students have access to the library.' },
  { term: 'accompany', meaning: 'v. 陪伴；伴随', example: 'I will accompany you home.' },
  { term: 'accomplish', meaning: 'v. 完成；实现', example: 'She accomplished her goal.' },
  { term: 'accurate', meaning: 'adj. 准确的；精确的', example: 'The data is highly accurate.' },
  { term: 'achieve', meaning: 'v. 达到；实现', example: 'Work hard to achieve success.' },
  { term: 'acquire', meaning: 'v. 获得；习得', example: 'Children acquire language quickly.' },
  { term: 'adapt', meaning: 'v. 适应；改编', example: 'We must adapt to changes.' },
  { term: 'adequate', meaning: 'adj. 充足的；适当的', example: 'We need adequate preparation.' },
  { term: 'adjust', meaning: 'v. 调整；适应', example: 'Adjust the chair to your height.' },
  { term: 'admire', meaning: 'v. 钦佩；欣赏', example: 'I admire her courage.' },
  { term: 'adopt', meaning: 'v. 采用；收养', example: 'They decided to adopt a new method.' },
  { term: 'advance', meaning: 'v./n. 前进；进步', example: 'Technology continues to advance.' },
  { term: 'advantage', meaning: 'n. 优势；有利条件', example: 'Speaking English is an advantage.' },
  { term: 'affect', meaning: 'v. 影响；感动', example: 'Weather affects our mood.' },
  { term: 'afford', meaning: 'v. 负担得起；提供', example: 'I can afford this book.' },
  { term: 'aggressive', meaning: 'adj. 好斗的；进取的', example: 'He is aggressive in business.' },
  { term: 'allocate', meaning: 'v. 分配；拨给', example: 'The school allocated funds for books.' },
  { term: 'alternative', meaning: 'n. 替代方案 adj. 替代的', example: 'We have no alternative but to wait.' },
  { term: 'ambition', meaning: 'n. 雄心；抱负', example: 'Her ambition is to be a doctor.' },
  { term: 'analyze', meaning: 'v. 分析', example: 'Scientists analyze the data.' },
  { term: 'ancient', meaning: 'adj. 古代的；古老的', example: 'They study ancient history.' },
  { term: 'annual', meaning: 'adj. 每年的；年度的', example: 'The annual meeting is in May.' },
  { term: 'anticipate', meaning: 'v. 预期；预料', example: 'We anticipate a busy day.' },
  { term: 'anxiety', meaning: 'n. 焦虑；担忧', example: 'He felt anxiety before the exam.' },
  { term: 'apparent', meaning: 'adj. 明显的；表面的', example: 'It was apparent she was tired.' },
];
